In [1]:
percent_of_test_data = 30

In [2]:
import sys
sys.path.append('/Users/tomek/OneDrive/Projects/Machine Learning/passat-b6-tdi')

import urllib.request
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from bs4 import BeautifulSoup
import predict

print(sys.path)


['', 'c:\\users\\tomek\\appdata\\local\\programs\\python\\python36-32\\python36.zip', 'c:\\users\\tomek\\appdata\\local\\programs\\python\\python36-32\\DLLs', 'c:\\users\\tomek\\appdata\\local\\programs\\python\\python36-32\\lib', 'c:\\users\\tomek\\appdata\\local\\programs\\python\\python36-32', 'c:\\users\\tomek\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages', 'c:\\users\\tomek\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\tomek\\.ipython', '/Users/tomek/OneDrive/Projects/Machine Learning/passat-b6-tdi']


In [3]:
main_url = 'https://www.otomoto.pl/osobowe/volkswagen/passat/b6-2005-2010/?search%5Bfilter_enum_fuel_type%5D%5B0%5D=diesel&search%5Bfilter_enum_damaged%5D=0&search%5Bcountry%5D='
html = urllib.request.urlopen(main_url).read()
soup = BeautifulSoup(html,"lxml")

pages = int(soup.find_all('span', attrs={'class': 'page'})[-2].text)
print('Found pages: ',pages)

Found pages:  51


In [4]:
Xy = predict.collect_data(main_url)

Page: 1 | Offers: 32


Page: 2 | Offers: 32


Page: 3 | Offers: 32


Page: 4 | Offers: 32


Page: 5 | Offers: 32


Page: 6 | Offers: 32


Page: 7 | Offers: 32


Page: 8 | Offers: 32


Page: 9 | Offers: 32


In [8]:
print(Xy.shape)
print(Xy[-10:])

X_train, y_train, X_test, y_test = predict.split_data(Xy, percent_of_test_data) 

#print(X.shape)
#print(y.shape)

(254, 4)
[[   2009.  233000.    1968.   29900.]
 [   2005.  209000.    1968.   17400.]
 [   2006.  247000.    1968.   26000.]
 [   2007.   34000.    1896.   23900.]
 [   2005.  158351.    1896.   15200.]
 [   2007.  200673.    1968.   19000.]
 [   2007.  236500.    1968.   22000.]
 [   2007.  219000.    1896.   19900.]
 [   2007.  127673.    1968.   31000.]
 [   2007.  182277.    1968.   22900.]]

Total samples:  254
Training samples: 178
Test samples: 76


In [135]:
regr = linear_model.LinearRegression(normalize=True)
regr.fit(X_train, y_train)

np.set_printoptions(formatter={'float_kind':'{:f}'.format})
print('Interceptor: ',regr.intercept_)
print('Coefficients: ', regr.coef_)

Interceptor:  [-4496755.400145]
Coefficients:  [[2253.339482 -0.028307 1.415770]]


In [136]:
y_pred = regr.predict(X_test)

#print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print('Variance score: %.2f' % r2_score(y_test, y_pred))

Variance score: 0.68


In [137]:
price_pred = regr.predict([[2010,180000, 1968]])
print('The best price for your Passat B6 is '+str(round(price_pred[0][0],2))+' PLN')

The best price for your Passat B6 is 30148.01 PLN
